"""Deterministic perception adversarial probe (dev tooling).

These cases vary grammatical role and entity surface form rather than adding biology
synonyms.  They protect the two firewall invariants while attacking the remaining
rules-mode perception surface:

* graph entities must resolve across case/spacing/hyphen/plural formatting;
* direction follows origin/destination roles, including passive and oblique origins;
* scientific prose must not be mistaken for a graph command;
* pending resolution must identify the right subject and structured failures must
  take precedence over incidental OOD vocabulary.

ENFORCED cases must pass (the run exits nonzero otherwise). A second block of
KNOWN RESIDUALS (DP5-DP9) attacks event-local negation/modality/comparator scope;
these need clause-boundary and NegEx-termination work this implementation has not
adopted, so they are reported visibly as XFAILs rather than quietly omitted — the
same discipline the former direction_probe N8 hole followed. Do not delete them;
they mark exactly where the next perception work should land.

Run: python3 tests/deterministic_perception_probe.py
"""
from __future__ import annotations

import os
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from groundtruth.harness import run
from groundtruth.ingest import EvidenceItem
from groundtruth.loader import load_seed
from groundtruth.model import GraphView
from starter.my_solution import extract, ingest


def P(groups="many", repl=5, method="defined_factor_perturbation",
      direct="direct", effect="strong", retr="none"):
    return {"replication_count": repl, "independent_groups": groups,
            "method_class": method, "method_directness": direct,
            "effect_strength": effect, "retraction_status": retr}


def revised(result):
    return any(d.op == "revise_confidence" for d in result.deltas)


def op(result, name):
    return any(d.op == name for d in result.deltas)


def attributed(result, evidence_id):
    return bool(result.deltas) and all(d.evidence_id == evidence_id for d in result.deltas)


def single_cases():
    cases = []

    # Entity formatting is not semantics. This wording contains no lateral keyword,
    # so only successful graph grounding can produce the structural regime verdict.
    body = "fibroblast became neuron."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP1", "", body, P()), GraphView(load_seed()))
    cases.append(("DP1 lowercase entities ground; structural lateral OOD",
                  {s.name for s in frame.entities} == {"Fibroblast", "Neuron"}
                  and result.ood_flag and op(result, "propose_regime"),
                  f"entities={[s.name for s in frame.entities]} ood={result.ood_flag} ops={[d.op for d in result.deltas]}"))

    body = "fibroblasts returned to pluripotent-stem-cells under defined factors."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP2", "", body, P()), GraphView(load_seed()))
    cases.append(("DP2 plural/hyphen entities ground end-to-end",
                  {s.name for s in frame.entities} == {"Fibroblast", "PluripotentStemCell"}
                  and revised(result) and not result.ood_flag,
                  f"entities={[s.name for s in frame.entities]} direction={frame.direction} ops={[d.op for d in result.deltas]}"))

    # The source is the object of a source-material phrase. Entity order is
    # destination-first; role recognition must prevent the backward default.
    body = "Fibroblast populations arose in cultures seeded with PluripotentStemCell."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP3", "", body, P()), GraphView(load_seed()))
    cases.append(("DP3 oblique 'seeded with' source resolves forward (closes N8)",
                  frame.direction == "forward" and not revised(result),
                  f"direction={frame.direction} ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = "PluripotentStemCell populations arose in cultures seeded with Fibroblast."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP3B", "", body, P()), GraphView(load_seed()))
    cases.append(("DP3B 'seeded with' backward-role mirror still revises",
                  frame.direction == "backward" and revised(result) and not result.ood_flag,
                  f"direction={frame.direction} ops={[d.op for d in result.deltas]}"))

    body = "Fibroblast cells were generated by PluripotentStemCell cultures under standard conditions."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP4", "", body, P(method="observational")), GraphView(load_seed()))
    cases.append(("DP4 passive 'generated by' source resolves forward",
                  frame.direction == "forward" and not revised(result),
                  f"direction={frame.direction} ops={[d.op for d in result.deltas]}"))

    body = "PluripotentStemCell cells were generated by Fibroblast cultures under standard conditions."
    frame = extract(body, GraphView(load_seed()))
    result = ingest(EvidenceItem("DP4B", "", body, P(method="observational")), GraphView(load_seed()))
    cases.append(("DP4B passive 'generated by' backward-role mirror revises",
                  frame.direction == "backward" and revised(result) and not result.ood_flag,
                  f"direction={frame.direction} ops={[d.op for d in result.deltas]}"))

    # Mirror of the comparator/consequence residuals below: comma locality must not
    # split a single transition merely because an appositive treatment phrase
    # interrupts its endpoints. Enforced — main's clause splitter already handles it.
    body = "Fibroblast, after defined-factor treatment, became Neuron."
    result = ingest(EvidenceItem("DP8B", "", body, P()), GraphView(load_seed()))
    cases.append(("DP8B appositive commas preserve a real lateral transition",
                  result.ood_flag and op(result, "propose_regime"),
                  f"ood={result.ood_flag} ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = ("Defined factors override the developmental barrier and returned Fibroblast "
            "to PluripotentStemCell in four independent laboratories.")
    result = ingest(EvidenceItem("DP10", "", body, P()), GraphView(load_seed()))
    cases.append(("DP10 scientific 'override the barrier' is not an injection",
                  revised(result) and "instruction" not in result.rationale,
                  f"ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    # Emit-side regression gate: every operation, mutating or not, remains tied
    # to the active item. This is expected to pass today but protects later fixes.
    rich = ingest(EvidenceItem("DP11", "",
        "Fibroblast returned to PluripotentStemCell under defined factors.", P()),
        GraphView(load_seed()))
    cases.append(("DP11 every emitted delta is attributed to the active evidence",
                  attributed(rich, "DP11"),
                  f"evidence_ids={[d.evidence_id for d in rich.deltas]}"))
    return cases


def sequence_cases():
    cases = []

    thin = P(groups=1, repl=1)
    retracted = P(groups=1, repl=1, retr="retracted")
    stream = [
        EvidenceItem("DPS1-A", "", "A single lab reports Fibroblasts returned to pluripotent stem cells. Not replicated.", thin),
        EvidenceItem("DPS1-B", "", "The earlier Fibroblast result has been retracted.", retracted),
    ]
    g = load_seed()
    records = run(stream, ingest, g).records
    cases.append(("DPS1 formatted entity pending resolves on structured retraction",
                  "hold_pending" in records[0].applied_ops
                  and "drop_claim" in records[1].applied_ops and not g.pending,
                  f"ops={[r.applied_ops for r in records]} pending={list(g.pending)}"))

    # Two pending results share the source-state destination. A pluralized terminal
    # mention must select its own pending claim, never the first item sharing PSC.
    stream = [
        EvidenceItem("DPS2-A", "", "A single lab reports Neuron returned to PluripotentStemCell. Not replicated.", thin),
        EvidenceItem("DPS2-B", "", "A single lab reports Fibroblast returned to PluripotentStemCell. Not replicated.", thin),
        EvidenceItem("DPS2-C", "", "Fibroblasts returned to PluripotentStemCell in four independent laboratories.", P(groups=4, repl=4)),
    ]
    g = load_seed()
    records = run(stream, ingest, g).records
    cases.append(("DPS2 corroboration drops exact pending subject, not common destination",
                  "drop_claim" in records[2].applied_ops
                  and "pending::Neuron+PluripotentStemCell" in g.pending
                  and "pending::Fibroblast+PluripotentStemCell" not in g.pending,
                  f"third_ops={records[2].applied_ops} pending={list(g.pending)}"))

    stream = [
        EvidenceItem("DPS3-A", "", "A single lab reports Fibroblast returned to PluripotentStemCell. Not replicated.", thin),
        EvidenceItem("DPS3-B", "", "The earlier reprogramming result in aged Fibroblast cells has been retracted.", retracted),
    ]
    g = load_seed()
    records = run(stream, ingest, g).records
    cases.append(("DPS3 structured failure resolves before incidental OOD vocabulary",
                  "drop_claim" in records[1].applied_ops and not records[1].ood_flag and not g.pending,
                  f"second_ops={records[1].applied_ops} ood={records[1].ood_flag} pending={list(g.pending)}"))

    return cases


def residual_cases():
    """Known residuals (XFAIL): event-local negation/modality/comparator scope.

    Each attacks a whole-body vs. clause-local reading of a suppression cue. They
    require clause-boundary segmentation and NegEx-style scope termination that this
    implementation has not adopted (the higher-regression-risk part of PR #5, kept
    out of the salvage). Tracked visibly so the hole is recorded, not hidden.
    """
    cases = []

    body = "No abnormalities were observed and Fibroblast cells returned to PluripotentStemCell under defined factors."
    result = ingest(EvidenceItem("DP5", "", body, P()), GraphView(load_seed()))
    cases.append(("DP5 unrelated negation does not swallow asserted result",
                  revised(result) and not result.ood_flag,
                  f"ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = ("Prior work asked if reversion was possible, and this study shows "
            "Fibroblast returned to PluripotentStemCell in four independent laboratories.")
    result = ingest(EvidenceItem("DP6", "", body, P()), GraphView(load_seed()))
    cases.append(("DP6 historical hypothetical does not suppress current result",
                  revised(result) and not result.ood_flag,
                  f"ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = "Fibroblast returned to PluripotentStemCell, a result that would be transformative."
    result = ingest(EvidenceItem("DP7", "", body, P()), GraphView(load_seed()))
    cases.append(("DP7 consequence modality does not suppress preceding fact",
                  revised(result) and not result.ood_flag,
                  f"ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = "Unlike Neuron controls, Fibroblast cells returned to PluripotentStemCell under defined factors."
    result = ingest(EvidenceItem("DP8", "", body, P()), GraphView(load_seed()))
    cases.append(("DP8 comparator state does not fabricate lateral OOD",
                  revised(result) and not result.ood_flag,
                  f"ood={result.ood_flag} ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    body = "Aged Fibroblast cells served as controls in a routine observational study."
    result = ingest(EvidenceItem("DP9", "", body, P(method="observational")), GraphView(load_seed()))
    cases.append(("DP9 incidental age adjective is not an age-axis result",
                  not result.ood_flag and not revised(result),
                  f"ood={result.ood_flag} ops={[d.op for d in result.deltas]} rationale={result.rationale}"))

    return cases


def main():
    checks = single_cases() + sequence_cases()
    print("=" * 78)
    print("DETERMINISTIC PERCEPTION ADVERSARIAL PROBE")
    print("=" * 78)
    print("ENFORCED:")
    failed = []
    for name, ok, detail in checks:
        if not ok:
            failed.append(name)
        print(f"  {'PASS' if ok else 'FAIL':4}  {name}")
        print(f"        {detail}")

    residuals = residual_cases()
    print("-" * 78)
    print("KNOWN RESIDUALS (XFAIL — tracked, not enforced):")
    for name, ok, detail in residuals:
        # An XFAIL that starts passing is worth surfacing (a residual got fixed) but
        # is not a failure of this run.
        print(f"  {'XPASS' if ok else 'XFAIL':5} {name}")
        print(f"        {detail}")

    print("-" * 78)
    print(f"  {len(checks) - len(failed)}/{len(checks)} enforced pass"
          + ("" if not failed else f"  |  RED: {[n.split()[0] for n in failed]}")
          + f"   ({sum(ok for _, ok, _ in residuals)}/{len(residuals)} residuals now passing)")
    print("=" * 78)
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
